volumes:
  gitlab-data:
    external: true
  runner_config:
    external: true
  gitlab-config:
    external: true
  gitlab-log:
    external: true
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab.web'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.web:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-log:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'